set_property SRC_FILE_INFO {cfile:{H:/Semester 7/CA/Lab/Lab2/uart-github/verilog-uart-working/for_fpga/check_project/check_display_of_fpga/check_display_of_fpga.srcs/constrs_1/new/constraints_check_display_of_fpga.xdc} rfile:../../../check_display_of_fpga.srcs/constrs_1/new/constraints_check_display_of_fpga.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk_i]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports rst_i]
